version: 2.1

orbs:
  node: circleci/node@4.1
  heroku: circleci/heroku@1.2.6
  sonarcloud: sonarsource/sonarcloud@1.0.2

jobs:
  build-and-test:
    docker:
      - image: cimg/node:15.1

    working_directory: ~/build

    steps:
      - checkout
      - node/install-packages

      - run:
          name: Install dependecies
          command: npm install

      - run:
          name: Run tests
          command: npm run test:coverage

      - store_artifacts:
          path: coverage

      - run:
          name: Build application
          command: npm run build
      
      - sonarcloud/scan:
          sonar_token_variable_name: SONAR_TOKEN 

workflows:
  version: 2

  -build:
    jobs:
      - build-and-test
      - heroku/deploy-via-git:
          requires:
            - build-and-test
          filters:
            branches:
              only: master